--[[
	Generated by Game Module Maker.
	
	A player can load in before the entire place inserts. This means they won't get StarterGui/PlayerScripts,
	since they're inserted to those services by the module after the player tries to copy them.
	
	This uses a LocalScript to ensure contents of StarterPlayerScripts and StarterGui are given to your player.
	A server script needs to distribute this to ensure the player gets it.
--]]

local StarterGui = game:GetService("StarterGui")
local StarterPlayer = game:GetService("StarterPlayer")
local StarterPlayerScripts = StarterPlayer:WaitForChild("StarterPlayerScripts")
local StarterCharacterScripts = StarterPlayer:WaitForChild("StarterCharacterScripts")
local EnsureReplicationScript = script:WaitForChild("EnsureLocalReplication")

local Connections = {}

game.Players.PlayerRemoving:Connect(function(player)
	Connections[player] = nil
end)


function EnsureReplicated(player, container, target)
	if Connections[player] == nil then
		Connections[player] = {}
	end

	if Connections[player][container] == nil then
		Connections[player][container] = container.ChildAdded:Connect(function()
			EnsureReplicated(player, container, target)
		end)
	end

	for _, child in ipairs(container:GetChildren()) do
		if target:FindFirstChild(child.Name) == nil and child.Archivable then
			child:Clone().Parent = target
		end
	end
end


function HandlePlayer(player)

	local playerGui = player:WaitForChild("PlayerGui")

	-- Need to put this script in PlayerGui since PlayerScripts doesn't exist on the server...
	EnsureReplicationScript:Clone().Parent = playerGui

	-- we don't care about the garbage below
	-- Wait for the character to spawn, because that's when we know that the client tried to copy scripts
	--[[if player.Character == nil then
		player.CharacterAdded:Wait()
	end
	
	if player.Character then
		EnsureReplicated(player, StarterCharacterScripts, player.Character)
		EnsureReplicated(player, StarterGui, playerGui)
	end]]
end

-- For some reason, game:IsLoaded() always returns false on the server in some places???
--repeat wait(0.1) until game:IsLoaded()
wait(0.1)

game.Players.PlayerAdded:Connect(HandlePlayer)

for _, player in ipairs(game.Players:GetPlayers()) do
	HandlePlayer(player)
end